# Generated by Django 3.1.5 on 2021-03-26 02:56

import django.db.models.deletion
import django_migration_linter as linter
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("helps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="notice",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
