# Generated by Django 3.1.5 on 2021-03-31 03:44

import django_migration_linter as linter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helps", "0002_notice_author"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-is_pinned", "-id"]},
        ),
        migrations.AddField(
            model_name="notice",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
