# Generated by Django 3.1.5 on 2022-02-18 06:03

from django.db import migrations, models


def insert_dongs(apps, schema_editor):
    Dong = apps.get_model("addresses", "Dong")
    f = open(
        "addresses\dong_datas.txt",
    )
    for d in f.readlines():
        data = d.strip().split("\t")
        sigungu = data[0][2:5]
        dong = data[0][5:8]
        li = data[0][8:10]
        # 리 포함된 곳은 뺌. 그럼 검색결과 너무 많아서 읍까지만 생성하도록 만듬.
        if data[2] == "존재" and sigungu != "00" and dong != "000" and li == "00":
            Dong.objects.create(dongcode=data[0], name=data[1])


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dong",
            fields=[
                ("dongcode", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(code=insert_dongs, reverse_code=migrations.RunPython.noop),
    ]
