# Generated by Django 3.0.7 on 2020-07-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=45)),
                ('account_number', models.CharField(blank=True, max_length=45)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('average_response_time', models.FloatField(default=0)),
                ('response_rate', models.FloatField(default=0)),
                ('contract_success_rate', models.FloatField(default=0)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('register_number', models.CharField(blank=True, max_length=45)),
                ('shop_name', models.CharField(blank=True, max_length=100)),
                ('shop_address', models.CharField(blank=True, max_length=200)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert', to='profiles.Profile')),
            ],
        ),
    ]
