# Generated by Django 3.1.5 on 2021-02-26 07:53

from django.db import migrations, models
from profiles.models import Profile

def change_bankname_to_bankcode(apps, schema_editor):
    bank_category_dict = dict((y, x) for x, y in Profile.BANK_CATEGORY)

    for profile in Profile.objects.all():
        if profile.bank_name == '신한' or profile.bank_name == '국민':
            profile.bank_name = bank_category_dict[profile.bank_name+"은행"]
        elif profile.bank_name == '':
            profile.bank_name = ''
        else:
            profile.bank_name = bank_category_dict[profile.bank_name]
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210225_1116'),
    ]

    operations = [
        migrations.RunPython(change_bankname_to_bankcode),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('', '은행명'), ('002', '산업은행'), ('032', '부산은행'), ('003', '기업은행'), ('034', '광주은행'), ('004', '국민은행'), ('035', '제주은행'), ('007', '수협'), ('037', '전북은행'), ('011', '농협은행'), ('039', '경남은행'), ('012', '지역농축협'), ('045', '새마을금고'), ('020', '우리은행'), ('048', '신용협동조합'), ('023', 'SC제일은행'), ('050', '상호저축은행'), ('027', '한국씨티은행'), ('064', '산림조합'), ('081', 'KEB하나은행'), ('071', '우체국'), ('088', '신한은행'), ('089', 'K뱅크'), ('031', '대구은행'), ('090', '카카오뱅크')], max_length=3),
        ),
    ]
