# Generated by Django 3.1.5 on 2021-03-25 04:40

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210226_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-is_default', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='garantee_insurance',
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '폐업'), (1, '요청'), (2, '승인'), (3, '거부')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.SmallIntegerField(choices=[(0, '은행명'), (2, '산업은행'), (32, '부산은행'), (3, '기업은행'), (34, '광주은행'), (4, '국민은행'), (35, '제주은행'), (7, '수협'), (37, '전북은행'), (11, '농협은행'), (39, '경남은행'), (12, '지역농축협'), (45, '새마을금고'), (20, '우리은행'), (48, '신용협동조합'), (23, 'SC제일은행'), (50, '상호저축은행'), (27, '한국씨티은행'), (64, '산림조합'), (81, 'KEB하나은행'), (71, '우체국'), (88, '신한은행'), (89, 'K뱅크'), (31, '대구은행'), (90, '카카오뱅크')], default=0),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models.get_file_path)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('expert_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='profiles.expertprofile')),
            ],
            options={
                'ordering': ['-to_date'],
            },
        ),
    ]
