# Generated by Django 3.0.7 on 2020-07-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_type', models.CharField(max_length=10)),
                ('lot_area', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('building_structure', models.CharField(max_length=100)),
                ('building_type', models.CharField(max_length=100)),
                ('building_area', models.SmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('trade_type', models.PositiveSmallIntegerField(choices=[(1, '월세'), (2, '전세'), (3, '매매'), (4, '교환')], default=1)),
                ('address', models.CharField(max_length=250)),
                ('realestate_type', models.PositiveSmallIntegerField(choices=[(1, '원룸'), (2, '투룸'), (3, '쓰리룸'), (4, '포룸'), (5, '쉐어하우스'), (6, '오피스텔'), (20, '아파트'), (21, '빌라'), (22, '단독주택'), (23, '상가주택'), (40, '상가'), (41, '토지')], default=1)),
                ('security_deposit', models.BigIntegerField(blank=True, null=True)),
                ('down_payment', models.BigIntegerField(blank=True, null=True)),
                ('monthly_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('maintenance_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('special_agreement', models.TextField(blank=True)),
                ('seller_signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('buyer_signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '작성중'), (2, '완료'), (3, '숨김')], default=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_papers', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_papers', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_papers', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTemplate',
            fields=[
                ('paper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='papers.Paper')),
            ],
            bases=('papers.paper',),
        ),
    ]
