# Generated by Django 3.1.5 on 2021-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_auto_20210326_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperstatus",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "요청중"), (2, "작성중"), (3, "서명중"), (0, "완료")], default=2
            ),
        ),
    ]
