# Generated by Django 3.1.5 on 2021-04-15 02:24

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_auto_20210330_1301"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name="verifyingexplanation",
            name="actual_building_category",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name="verifyingexplanation",
            name="ledger_building_category",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
