# Generated by Django 3.1.5 on 2021-04-15 06:07

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0004_auto_20210415_1124"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name="verifyingexplanation",
            name="noise_status",
        ),
        migrations.RemoveField(
            model_name="verifyingexplanation",
            name="sunshine_status",
        ),
        migrations.RemoveField(
            model_name="verifyingexplanation",
            name="vibration",
        ),
        migrations.RemoveField(
            model_name="verifyingexplanation",
            name="wall_paper_status",
        ),
        migrations.AddField(
            model_name="verifyingexplanation",
            name="noise_status",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifyingexplanation",
            name="sunshine_status",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifyingexplanation",
            name="vibration",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifyingexplanation",
            name="wall_paper_status",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
