# Generated by Django 3.1.5 on 2021-06-14 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("papers", "0005_auto_20210415_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="title",
            field=models.CharField(default="쉐어하우스 월세 계약서", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paper",
            name="voters",
            field=models.ManyToManyField(related_name="vote_papers", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="answer",
            name="voters",
            field=models.ManyToManyField(related_name="vote_answers", to=settings.AUTH_USER_MODEL),
        ),
    ]
