# Generated by Django 3.1.5 on 2021-08-25 18:29

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0007_auto_20210726_1015"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RenameField(
            model_name="paper",
            old_name="special_agreement",
            new_name="contract_details",
        ),
    ]
