# Generated by Django 3.1.5 on 2021-09-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0008_auto_20210826_0329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifyingexplanation",
            name="actual_building_category",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="verifyingexplanation",
            name="ledger_building_category",
            field=models.CharField(max_length=13),
        ),
    ]
