version: "2"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile-django-stage
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
