version: "2"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile-vue-dev
    ports:
      - 5050:5050
    container_name: vue
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  django:
    build:
      context: .
      dockerfile: Dockerfile-django-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/onepaper/
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env.devdocker
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
