FROM python:3.8.3-slim
WORKDIR /onepaper

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install debugpy==1.5.1
RUN pip install -r requirements.txt 
# copy entrypoint.sh
RUN apt-get update && apt-get install -y netcat
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /onepaper/entrypoint.sh
RUN chmod +x /onepaper/entrypoint.sh
RUN mkdir /var/log/gunicorn/

COPY . .
RUN cp .env.staging .env
# run entrypoint.sh
ENTRYPOINT ["/onepaper/entrypoint.sh"]