[tool.black]
line-length = 99 # override black's default line-length
exclude = '/migrations/'

[tool.isort]
line_length = 99 # override black's default line-length
profile = "black" 
skip_gitignore = true
skip = ['frontend', 'migrations']