<template>
</template>

<script>
export default {
  name: "VerifyingExplanationEditor",
  props: {
    obj: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      paper_categories: null,
      explanation_evidences: null,
      explanation_evidence_info: null,
      address: {
        old_address: null
      },
      land_area: null,
      land_category: null,
      actual_land_category: null,
      net_area: null,
      land_share: null,
      year_of_completion: null,
      building_category: null,
      actual_building_category: null,
      building_structure: null,
      building_direction: null,
      seismic_design: null,
      seismic_capacity: null,
      legal_status: true,
      matters_of_violation: null,
      land_ownership: null,
      building_ownership: null,
      land_other: null,
      building_other: null,
      rental_housing_registration: null,
      use_area: null,
      use_district: null,
      use_zone: null,
      building_coverage_limit: null,
      floor_area_limit: null,
      planning_facilities: null,
      permission_report_zone: null,
      speculative_area: null,
      unit_planning_area_others: null,
      other_use_restriction: null,
      relative_with_roads: null,
      is_paved_rode: null,
      acessibility: null,
      bus_stop: null,
      bus_by_foot: null,
      bus_time_required: null,
      subway_station: null,
      subway_by_foot: null,
      subway_time_required: null,
      parking_lot: null,
      parking_lot_info: null,
      elementary_school: null,
      elementary_school_by_foot: null,
      elementary_school_time_required: null,
      middle_school: null,
      middle_school_by_foot: null,
      middle_school_time_required: null,
      high_school: null,
      high_school_by_foot: null,
      high_school_time_required: null,
      department_store: null,
      department_store_by_foot: null,
      department_store_time_required: null,
      medical_center: null,
      medical_center_by_foot: null,
      medical_center_time_required: null,
      security_office: null,
      management: null,
      undesirable_facilities: null,
      undesirable_facilities_info: null,
      expected_transaction_price: null,
      land_prcie_recorded: null,
      building_price_recorded: null,
      acquisition_tax: null,
      special_tax: null,
      local_education_tax: null,
      water_damage_status: null,
      water_damage_location: null,
      water_capacity_status: null,
      water_capacity_location: null,
      electricity_supply_status: null,
      electricity_location: null,
      gas_supply_status: null,
      gas_supply_info: null,
      fire_alarm_detector: null,
      fire_alarm_detector_quantity: null,
      heating_supply_method: null,
      heating_status: null,
      heating_status_info: null,
      heating_type: null,
      heating_type_info: null,
      is_elevator: null,
      elevator_status: null,
      drainage_status: null,
      drainage_status_info: null,
      other_facilities: null,
      wall_crack_status: null,
      wall_crack_status_info: null,
      water_leak_status: null,
      water_leak_status_info: null,
      wall_paper_status: null,
      wall_paper_status_info: null,
      sunshine_status: null,
      sunshine_status_info: null,
      noise_status: null,
      vibration: null,
      comission: null,
      actual_expenses: null,
      payment_period: null,
      caculation_info: null
    }
  }
}
</script>

<style>

</style>