# Generated by Django 3.1.5 on 2022-02-04 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('item_category', models.PositiveSmallIntegerField(choices=[(1, '원룸'), (2, '투룸'), (3, '쓰리룸'), (4, '포룸'), (5, '쉐어하우스'), (6, '오피스텔'), (20, '아파트'), (21, '빌라'), (22, '단독주택'), (23, '상가주택'), (40, '상가'), (41, '토지'), (99, '기타')], default=1)),
                ('title', models.CharField(blank=True, max_length=25)),
                ('trade_category', models.PositiveSmallIntegerField(choices=[(1, '월세'), (2, '전세'), (3, '매매'), (4, '교환')], default=1)),
                ('online_visit', models.BooleanField(default=True)),
                ('short_lease', models.BooleanField(default=False)),
                ('down_payment', models.PositiveBigIntegerField(blank=True, default=0)),
                ('security_deposit', models.PositiveBigIntegerField(blank=True, default=0)),
                ('monthly_fee', models.PositiveIntegerField(blank=True, default=0)),
                ('maintenance_fee', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_default', models.BooleanField(blank=True, default=False, null=True)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addresses.address')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            bases=('addresses.address',),
        ),
    ]
