# Generated by Django 3.1.5 on 2022-04-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0002_listingstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="AskListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "원룸"),
                            (2, "투룸"),
                            (3, "쓰리룸"),
                            (4, "포룸"),
                            (5, "쉐어하우스"),
                            (6, "오피스텔"),
                            (20, "아파트"),
                            (21, "빌라"),
                            (22, "단독주택"),
                            (23, "상가주택"),
                            (40, "상가"),
                            (41, "토지"),
                            (99, "기타"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "trade_category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "월세"), (2, "전세"), (3, "매매"), (4, "교환")], default=1
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=25)),
                ("security_deposit", models.PositiveBigIntegerField(blank=True, default=0)),
                ("monthly_fee", models.PositiveIntegerField(blank=True, default=0)),
                ("maintenance_fee", models.PositiveIntegerField(blank=True, default=0)),
                ("online_visit", models.BooleanField(default=True)),
                ("term_of_lease", models.SmallIntegerField(default=12)),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("moving_date", models.DateField(blank=True, null=True)),
                ("content", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_asklistings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
