# Generated by Django 3.1.5 on 2022-04-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_asklisting_20220412_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='minimum_period',
            field=models.PositiveSmallIntegerField(default=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='short_lease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
