# Generated by Django 3.1.5 on 2022-05-23 02:24

import django_migration_linter as linter
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_auto_20220512_1254"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.DeleteModel(
            name="ListingStatus",
        ),
    ]
