# Generated by Django 3.1.5 on 2022-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_delete_listingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='secret_memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
