# Generated by Django 3.1.5 on 2022-06-23 00:34
import django_migration_linter
from django.db import migrations, models


def make_detail_address(apps, schema_editor):
    ListingAddress = apps.get_model("listings", "ListingAddress")

    for address in ListingAddress.objects.all():
        is_updated = False
        if address.dong != "" and address.dong != None:
            if address.dong[-1] != "동":
                address.detail = address.dong + "동"
            else:
                address.detail = address.dong
            is_updated = True
        if address.ho != "" and address.ho != None:
            ho = address.ho
            if is_updated:
                address.detail += " "
            else:
                address.detail = ""
            if ho[-1] != "호" and ho[-1] != "층":
                address.detail += ho + "호"
            else:
                address.detail += ho
            is_updated = True
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_secret_memo"),
    ]

    operations = [
        django_migration_linter.IgnoreMigration(),
        migrations.AlterField(
            model_name="listing",
            name="secret_memo",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(code=make_detail_address, reverse_code=migrations.RunPython.noop),
    ]
