version: "2"
services:
  jenkins:
    build: .
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    env_file:
      - ./.env
volumes:
  jenkins_data:
