version: "2"
services:
  jenkins:
    build: .
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/ubuntu/.ssh/id_rsa:/root/.ssh/id_rsa
    container_name: jenkins
    env_file:
      - ./.env
volumes:
  jenkins_data:
